// Generated by CoffeeScript 1.9.2
(function() {
  var indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  Array.prototype.random_node = function() {
    return this[Math.floor(Math.random() * this.length)];
  };

  Array.prototype.blacklist_rule = function(s) {
    var i, j, len, out;
    out = [];
    for (j = 0, len = this.length; j < len; j++) {
      i = this[j];
      if (i.indexOf(s) === -1) {
        out.push(i);
      }
    }
    return out;
  };

  Array.prototype.whitelist_rule = function(s) {
    var i, j, len, out;
    out = [];
    for (j = 0, len = this.length; j < len; j++) {
      i = this[j];
      if (indexOf.call(i, s) >= 0) {
        out.push(i);
      }
    }
    return out;
  };

  Array.prototype.remove_duplicates = function() {
    var i, j, len, out;
    out = [];
    for (j = 0, len = this.length; j < len; j++) {
      i = this[j];
      if (out.indexOf(i) === -1) {
        out.push(i);
      }
    }
    return out;
  };

}).call(this);
