// Generated by CoffeeScript 1.9.2
(function() {
  var array = "hello world or some other words and stuff".split(" ");
  Array.prototype.randomNode = function() {
    return this[Math.floor(Math.random() * this.length)];
  };
  console.log(array.randomNode());

}).call(this);
