// Generated by CoffeeScript 1.9.2

/*
    Prototype extensions for javascript strings 
    Author: Cody Kochmann

    To do list:
    [X] - contains
    [X] - remove_all
    [X] - word_count
    [X] - base64_encode
    [X] - base64_decode
    [ ] - find_all
    [ ] - count_sentences
    [ ] - longest_word
    [ ] - most_common_word
    [ ] - most_common_pattern
    [ ] - is_multi_line
    [ ] - find_lines_containing
    [ ] - spell_check
    [ ] - reading_level
    [ ] - estimate_type
 */

(function() {
  String.prototype.contains = function(search_str) {
    if (this.indexOf(search_str) === -1) {
      return false;
    }
    return true;
  };

  String.prototype.remove_all = function(target) {
    if (this.indexOf(target) !== -1) {
      this.split(target).join('');
    }
  };

  String.prototype.word_count = function() {
    var count, i, letters, split, tmp_array;
    i = 0;
    count = 0;
    letters = 'abcdefghijklmnopqrstuvwxyz ';
    letters += letters.toUpperCase();
    tmp_array = this.split('');
    for (i in tmp_array) {
      if (letters.indexOf(tmp_array[i]) === -1) {
        this.split(tmp_array[i]).join('');
      }
    }
    while (this.indexOf('  ') !== -1) {
      this.replace('  ').join(' ');
    }
    split = this.split(' ');
    for (i in split) {
      if (split[i].length > 0 && split[i] !== ' ') {
        count += 1;
      }
    }
    return count;
  };

  String.prototype.base64_encode = function() {
    return window.btoa(unescape(encodeURIComponent(this)));
  };

  String.prototype.base64_decode = function() {
    return decodeURIComponent(escape(window.atob(this)));
  };

}).call(this);
